cd $HOME
cd /sdcard
mv Telegram BaapG-Telegram
mv .Telegram Telegram
mv .browser browser
mv .GBWhatsApp GBWhatsApp
mv .BGMI BGMI
mv .ApkEditor ApkEditor
mv Download BaapG-Download
mv .Download Download
mv Instagram Instagram2
mv .Instagram Instagram
mv .SHAREit SHAREit
mv .bluetooth bluetooth
mv .VidMate VidMate
mv .YoWhatsApp YoWhatsApp
mv DCIM BAAPG-DCIM
mv .DCIM DCIM
mv .GBWhatsApp GBWhatsApp
mv Android Android-BaapG
mv .Android Android
mv .documents documents
mv .IMO IMO
mv .Movies Movies
mv .MT2 MT2
mv WhatsApp BaapG-WhatsApp
mv .WhatsApp WhatsApp
mv .sketchware sketchware
mv Pictures BaapG-Picture
mv .Pictures Pictures
mv .YoWhatsApp YoWhatsApp
